import * as fs from 'node:fs';
import * as path from 'node:path';
import { Command } from 'commander';
import chalk from 'chalk';
import type { Severity } from '../../types/common.js';

const DEFAULT_CONFIG = `# g0 Configuration
# See: https://github.com/guard0-ai/g0

# Minimum score to pass CI/CD gate (0-100)
min_score: 70

# Minimum grade to pass (A, B, C, D, F)
# min_grade: C

# Severity threshold - fail if any finding at or above this level
# fail_on: critical

# Exclude specific rules
# exclude_rules:
#   - AA-DL-001  # verbose=True (acceptable in dev)

# Exclude paths from scanning
# exclude_paths:
#   - tests/
#   - docs/
#   - examples/

# Custom rules directory
# rules_dir: ./rules
`;

type HookType = 'pre-commit' | 'pre-push';
type HookManager = 'husky' | 'lefthook' | 'standalone';

interface InitOptions {
  force?: boolean;
  hook?: boolean;
  hooks?: boolean;
  hookType?: string;
  hookManager?: string;
  minSeverity?: string;
}

const VALID_HOOK_TYPES: readonly string[] = ['pre-commit', 'pre-push'] as const;
const VALID_HOOK_MANAGERS: readonly string[] = ['husky', 'lefthook', 'standalone'] as const;
const VALID_SEVERITIES: readonly string[] = ['critical', 'high', 'medium', 'low', 'info'] as const;

export const initCommand = new Command('init')
  .description('Initialize g0 configuration file')
  .option('-f, --force', 'Overwrite existing config')
  .option('--hook', 'Install git hook for g0 scan')
  .option('--hooks', 'Install git hook (alias for --hook)')
  .option('--hook-type <type>', 'Hook type: pre-commit or pre-push (default: pre-commit)')
  .option('--hook-manager <manager>', 'Hook manager: husky, lefthook, or standalone (default: auto-detect)')
  .option('--min-severity <severity>', 'Minimum severity to block on (default: high)')
  .action((options: InitOptions) => {
    if (options.hook || options.hooks) {
      const hookType = (options.hookType ?? 'pre-commit') as HookType;
      if (!VALID_HOOK_TYPES.includes(hookType)) {
        console.error(chalk.red(`Invalid hook type: ${hookType}. Must be one of: ${VALID_HOOK_TYPES.join(', ')}`));
        process.exit(1);
      }

      const minSeverity = (options.minSeverity ?? 'high') as Severity;
      if (!VALID_SEVERITIES.includes(minSeverity)) {
        console.error(chalk.red(`Invalid severity: ${minSeverity}. Must be one of: ${VALID_SEVERITIES.join(', ')}`));
        process.exit(1);
      }

      const manager = (options.hookManager ?? detectHookManager()) as HookManager;
      if (!VALID_HOOK_MANAGERS.includes(manager)) {
        console.error(chalk.red(`Invalid hook manager: ${manager}. Must be one of: ${VALID_HOOK_MANAGERS.join(', ')}`));
        process.exit(1);
      }

      installHook({ hookType, manager, minSeverity, force: options.force });
      return;
    }

    const configPath = path.join(process.cwd(), '.g0.yaml');

    if (fs.existsSync(configPath) && !options.force) {
      console.log(chalk.yellow('Config file already exists: .g0.yaml'));
      console.log(chalk.dim('Use --force to overwrite'));
      return;
    }

    fs.writeFileSync(configPath, DEFAULT_CONFIG, 'utf-8');
    console.log(chalk.green('Created .g0.yaml'));
    console.log(chalk.dim('Run `g0 scan` to scan your project'));
  });

/**
 * Detect which hook manager is in use in the current project.
 */
export function detectHookManager(): HookManager {
  const cwd = process.cwd();

  // Check for Husky directory
  if (fs.existsSync(path.join(cwd, '.husky'))) {
    return 'husky';
  }

  // Check for lefthook config
  if (
    fs.existsSync(path.join(cwd, 'lefthook.yml')) ||
    fs.existsSync(path.join(cwd, 'lefthook.yaml'))
  ) {
    return 'lefthook';
  }

  // Check package.json for husky/lefthook deps
  const pkgPath = path.join(cwd, 'package.json');
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as Record<string, Record<string, unknown>>;
      const allDeps: Record<string, unknown> = {
        ...(pkg.dependencies as Record<string, unknown> | undefined),
        ...(pkg.devDependencies as Record<string, unknown> | undefined),
      };
      if (allDeps.husky) return 'husky';
      if (allDeps.lefthook) return 'lefthook';
    } catch {
      // ignore parse errors
    }
  }

  return 'standalone';
}

function generateHookScript(hookType: HookType, minSeverity: Severity): string {
  const scanCmd = `g0 scan --ci --severity ${minSeverity}`;
  return `#!/bin/sh
# g0 ${hookType} hook — auto-generated by \`g0 init --hook\`
# To bypass: git commit --no-verify (use with caution!)
set -e

echo "[g0] Running security scan (${hookType})..."
${scanCmd}
echo "[g0] Security scan passed."
`;
}

interface InstallHookOptions {
  hookType: HookType;
  manager: HookManager;
  minSeverity: Severity;
  force?: boolean;
}

function installHookHusky(hookType: HookType, minSeverity: Severity, force?: boolean): void {
  const huskyDir = path.join(process.cwd(), '.husky');
  if (!fs.existsSync(huskyDir)) {
    fs.mkdirSync(huskyDir, { recursive: true });
  }

  const hookPath = path.join(huskyDir, hookType);
  if (fs.existsSync(hookPath) && !force) {
    console.log(chalk.yellow(`⚠ Husky hook already exists: .husky/${hookType}`));
    console.log(chalk.dim('Use --force to overwrite'));
    return;
  }

  const script = generateHookScript(hookType, minSeverity);
  fs.writeFileSync(hookPath, script, { mode: 0o755 });
  console.log(chalk.green(`✓ Created .husky/${hookType}`));
  console.log(chalk.dim(`  Runs: g0 scan --ci --severity ${minSeverity}`));
  console.log(chalk.dim('  Bypass with: git commit --no-verify'));
}

function installHookLefthook(hookType: HookType, minSeverity: Severity, force?: boolean): void {
  const configName = fs.existsSync(path.join(process.cwd(), 'lefthook.yaml'))
    ? 'lefthook.yaml'
    : 'lefthook.yml';
  const configPath = path.join(process.cwd(), configName);

  let existing = '';
  if (fs.existsSync(configPath)) {
    existing = fs.readFileSync(configPath, 'utf-8');
    if (existing.includes('g0 scan') && !force) {
      console.log(chalk.yellow('⚠ lefthook config already contains g0 scan'));
      console.log(chalk.dim('Use --force to overwrite'));
      return;
    }
  }

  const block = `\n${hookType}:\n  commands:\n    g0-scan:\n      run: g0 scan --ci --severity ${minSeverity}\n`;

  if (existing && !force) {
    fs.appendFileSync(configPath, block, 'utf-8');
  } else {
    const content = existing ? existing + block : block.trimStart();
    fs.writeFileSync(configPath, content, 'utf-8');
  }

  console.log(chalk.green(`✓ Added g0 scan to ${configName} (${hookType})`));
  console.log(chalk.dim(`  Runs: g0 scan --ci --severity ${minSeverity}`));
}

function installHookStandalone(hookType: HookType, minSeverity: Severity, force?: boolean): void {
  const gitDir = path.join(process.cwd(), '.git');
  if (!fs.existsSync(gitDir)) {
    console.error(chalk.red('Not a git repository. Run `git init` first.'));
    process.exit(1);
  }

  const hooksDir = path.join(gitDir, 'hooks');
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  const hookPath = path.join(hooksDir, hookType);
  if (fs.existsSync(hookPath) && !force) {
    console.log(chalk.yellow(`⚠ Hook already exists: .git/hooks/${hookType}`));
    console.log(chalk.dim('Use --force to overwrite, or remove it manually.'));
    return;
  }

  const script = generateHookScript(hookType, minSeverity);
  fs.writeFileSync(hookPath, script, { mode: 0o755 });
  console.log(chalk.green(`✓ Installed ${hookType} hook`));
  console.log(chalk.dim(`  ${hookPath}`));
  console.log(chalk.dim(`  Runs: g0 scan --ci --severity ${minSeverity}`));
  console.log(chalk.dim('  Bypass with: git commit --no-verify'));
}

function installHook(opts: InstallHookOptions): void {
  const { hookType, manager, minSeverity, force } = opts;

  console.log(chalk.dim(`Hook manager: ${manager}`));

  switch (manager) {
    case 'husky':
      installHookHusky(hookType, minSeverity, force);
      break;
    case 'lefthook':
      installHookLefthook(hookType, minSeverity, force);
      break;
    case 'standalone':
      installHookStandalone(hookType, minSeverity, force);
      break;
  }
}
