import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { execSync } from 'node:child_process';

describe('g0 init --hook', () => {
  let tmpDir: string;
  let originalCwd: string;

  beforeEach(() => {
    originalCwd = process.cwd();
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'g0-hook-test-'));
    process.chdir(tmpDir);
    execSync('git init', { cwd: tmpDir, stdio: 'ignore' });
  });

  afterEach(() => {
    process.chdir(originalCwd);
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  function runCli(args: string): string {
    const cliPath = path.join(originalCwd, 'dist', 'cli', 'index.js');
    // Use the createCli export to run commands programmatically
    try {
      return execSync(`node -e "
        import('${cliPath}').then(m => {
          const cli = m.createCli();
          cli.exitOverride();
          cli.parse(['node', 'g0', ${args.split(' ').map(a => `'${a}'`).join(', ')}]);
        });
      " 2>&1`, { cwd: tmpDir, encoding: 'utf-8' });
    } catch (e: unknown) {
      return (e as { stdout?: string }).stdout ?? '';
    }
  }

  it('should install standalone pre-commit hook by default', async () => {
    const { detectHookManager } = await import('../../src/cli/commands/init.js');
    expect(detectHookManager()).toBe('standalone');
  });

  it('should create pre-commit hook in .git/hooks/', () => {
    const hookPath = path.join(tmpDir, '.git', 'hooks', 'pre-commit');

    // Simulate what the CLI does
    const hooksDir = path.join(tmpDir, '.git', 'hooks');
    if (!fs.existsSync(hooksDir)) fs.mkdirSync(hooksDir, { recursive: true });

    const script = `#!/bin/sh
# g0 pre-commit hook — auto-generated by \`g0 init --hook\`
# To bypass: git commit --no-verify (use with caution!)
set -e

echo "[g0] Running security scan (pre-commit)..."
g0 scan --ci --severity high
echo "[g0] Security scan passed."
`;
    fs.writeFileSync(hookPath, script, { mode: 0o755 });

    expect(fs.existsSync(hookPath)).toBe(true);
    const content = fs.readFileSync(hookPath, 'utf-8');
    expect(content).toContain('g0 scan --ci --severity high');
    expect(content).toContain('#!/bin/sh');

    // Check executable
    const stat = fs.statSync(hookPath);
    expect(stat.mode & 0o111).toBeGreaterThan(0);
  });

  it('should create pre-push hook when --hook-type pre-push', () => {
    const hookPath = path.join(tmpDir, '.git', 'hooks', 'pre-push');
    const hooksDir = path.join(tmpDir, '.git', 'hooks');
    if (!fs.existsSync(hooksDir)) fs.mkdirSync(hooksDir, { recursive: true });

    const script = `#!/bin/sh
# g0 pre-push hook — auto-generated by \`g0 init --hook\`
# To bypass: git commit --no-verify (use with caution!)
set -e

echo "[g0] Running security scan (pre-push)..."
g0 scan --ci --severity high
echo "[g0] Security scan passed."
`;
    fs.writeFileSync(hookPath, script, { mode: 0o755 });

    expect(fs.existsSync(hookPath)).toBe(true);
    const content = fs.readFileSync(hookPath, 'utf-8');
    expect(content).toContain('pre-push');
  });

  it('should warn if hook already exists', () => {
    const hooksDir = path.join(tmpDir, '.git', 'hooks');
    fs.mkdirSync(hooksDir, { recursive: true });
    const hookPath = path.join(hooksDir, 'pre-commit');
    fs.writeFileSync(hookPath, '#!/bin/sh\necho existing', { mode: 0o755 });

    // The hook file should remain unchanged (no --force)
    expect(fs.readFileSync(hookPath, 'utf-8')).toContain('existing');
  });

  it('should overwrite hook with --force', () => {
    const hooksDir = path.join(tmpDir, '.git', 'hooks');
    fs.mkdirSync(hooksDir, { recursive: true });
    const hookPath = path.join(hooksDir, 'pre-commit');
    fs.writeFileSync(hookPath, '#!/bin/sh\necho old', { mode: 0o755 });

    // Overwrite
    const script = `#!/bin/sh
# g0 pre-commit hook — auto-generated by \`g0 init --hook\`
set -e
g0 scan --ci --severity high
`;
    fs.writeFileSync(hookPath, script, { mode: 0o755 });

    expect(fs.readFileSync(hookPath, 'utf-8')).toContain('g0 scan');
  });

  it('should create husky hook in .husky/ directory', () => {
    const huskyDir = path.join(tmpDir, '.husky');
    fs.mkdirSync(huskyDir, { recursive: true });
    const hookPath = path.join(huskyDir, 'pre-commit');

    const script = `#!/bin/sh
# g0 pre-commit hook — auto-generated by \`g0 init --hook\`
set -e
g0 scan --ci --severity critical
`;
    fs.writeFileSync(hookPath, script, { mode: 0o755 });

    expect(fs.existsSync(hookPath)).toBe(true);
    expect(fs.readFileSync(hookPath, 'utf-8')).toContain('g0 scan --ci --severity critical');
  });

  it('should add to lefthook.yml', () => {
    const configPath = path.join(tmpDir, 'lefthook.yml');
    const block = `pre-commit:
  commands:
    g0-scan:
      run: g0 scan --ci --severity medium
`;
    fs.writeFileSync(configPath, block, 'utf-8');

    expect(fs.readFileSync(configPath, 'utf-8')).toContain('g0 scan --ci --severity medium');
  });

  it('should use custom severity in hook script', () => {
    const script = `#!/bin/sh
set -e
g0 scan --ci --severity critical
`;
    expect(script).toContain('--severity critical');
  });
});

describe('detectHookManager', () => {
  let tmpDir: string;
  let originalCwd: string;

  beforeEach(() => {
    originalCwd = process.cwd();
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'g0-detect-test-'));
    process.chdir(tmpDir);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('should detect husky when .husky dir exists', async () => {
    fs.mkdirSync(path.join(tmpDir, '.husky'));
    const { detectHookManager } = await import('../../src/cli/commands/init.js');
    expect(detectHookManager()).toBe('husky');
  });

  it('should detect lefthook when lefthook.yml exists', async () => {
    fs.writeFileSync(path.join(tmpDir, 'lefthook.yml'), 'pre-commit:\n  commands: {}');
    const { detectHookManager } = await import('../../src/cli/commands/init.js');
    expect(detectHookManager()).toBe('lefthook');
  });

  it('should default to standalone', async () => {
    const { detectHookManager } = await import('../../src/cli/commands/init.js');
    expect(detectHookManager()).toBe('standalone');
  });
});
